{
    "name": "AI Purchase Document Preview",
    "summary": "Extract supplier documents with selectable Gemini/OpenAI endpoints, review them, then create an RFQ",
    "version": "19.0.1.1.2",
    "category": "Purchases",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "purchase",
        "documents",
        "ai_app",
        "ai_server_actions",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/sequence.xml",
        "data/provider_config.xml",
        "data/ai_tools.xml",
        "views/ai_provider_config_views.xml",
        "views/ai_purchase_intake_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
