{
    "name": "Petty Cash Management",
    "summary": "Controlled petty cash funds, approvals, accounting, periods, and reports",
    "version": "19.0.2.0.5",
    "category": "Accounting/Accounting",
    "author": "Mehedi Hasan",
    "website": "https://www.zencoreltd.com",
    "images": ["static/description/icon.png"],
    "license": "LGPL-3",
    "depends": ["account", "hr", "mail"],
    "data": [
        "security/petty_cash_security.xml",
        "security/ir.model.access.csv",
        "security/petty_cash_simple_security.xml",
        "data/petty_cash_sequence.xml",
        "views/petty_cash_fund_views.xml",
        "views/petty_cash_category_views.xml",
        "views/petty_cash_period_views.xml",
        "views/petty_cash_transaction_views.xml",
        "views/petty_cash_request_views.xml",
        "views/petty_cash_dashboard_views.xml",
        "views/account_move_views.xml",
        "report/petty_cash_statement_report.xml",
        "views/petty_cash_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "petty_cash_management/static/src/fields/supporting_documents_field.js",
            "petty_cash_management/static/src/fields/supporting_documents_field.xml",
        ],
        "web.assets_unit_tests": [
            "petty_cash_management/static/src/fields/supporting_documents_field.js",
            "petty_cash_management/static/src/fields/supporting_documents_field.xml",
            "petty_cash_management/static/tests/supporting_documents_field.test.js",
        ],
    },
    "application": True,
    "installable": True,
}
